/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DrawerLayoutRouteRouteImport } from './routes/_drawer-layout/route'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as DrawerLayoutIndexRouteImport } from './routes/_drawer-layout/index'
import { Route as DrawerLayoutAuthRouteRouteImport } from './routes/_drawer-layout/auth/route'
import { Route as DrawerLayoutMeRouteRouteImport } from './routes/_drawer-layout/me/route'
import { Route as DrawerLayoutAuthLoginRouteImport } from './routes/_drawer-layout/auth/login'
import { Route as DrawerLayoutAuthSignUpRouteImport } from './routes/_drawer-layout/auth/sign-up'
import { Route as DrawerLayoutMeIndexRouteImport } from './routes/_drawer-layout/me/index'
import { Route as DrawerLayoutMeProfileRouteImport } from './routes/_drawer-layout/me/profile'
import { Route as DrawerLayoutMeSecurityRouteImport } from './routes/_drawer-layout/me/security'
import { Route as DrawerLayoutRoomsIndexRouteImport } from './routes/_drawer-layout/rooms/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const DrawerLayoutRouteRoute = DrawerLayoutRouteRouteImport.update({
  id: '/_drawer-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawerLayoutIndexRoute = DrawerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrawerLayoutRouteRoute,
} as any)
const DrawerLayoutAuthRouteRoute = DrawerLayoutAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DrawerLayoutRouteRoute,
} as any)
const DrawerLayoutMeRouteRoute = DrawerLayoutMeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => DrawerLayoutRouteRoute,
} as any)
const DrawerLayoutAuthLoginRoute = DrawerLayoutAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DrawerLayoutAuthRouteRoute,
} as any)
const DrawerLayoutAuthSignUpRoute = DrawerLayoutAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => DrawerLayoutAuthRouteRoute,
} as any)
const DrawerLayoutMeIndexRoute = DrawerLayoutMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrawerLayoutMeRouteRoute,
} as any)
const DrawerLayoutMeProfileRoute = DrawerLayoutMeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DrawerLayoutMeRouteRoute,
} as any)
const DrawerLayoutMeSecurityRoute = DrawerLayoutMeSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DrawerLayoutMeRouteRoute,
} as any)
const DrawerLayoutRoomsIndexRoute = DrawerLayoutRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => DrawerLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DrawerLayoutIndexRoute
  '/trial': typeof TrialRoute
  '/auth': typeof DrawerLayoutAuthRouteRouteWithChildren
  '/me': typeof DrawerLayoutMeRouteRouteWithChildren
  '/auth/login': typeof DrawerLayoutAuthLoginRoute
  '/auth/sign-up': typeof DrawerLayoutAuthSignUpRoute
  '/me/profile': typeof DrawerLayoutMeProfileRoute
  '/me/security': typeof DrawerLayoutMeSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me/': typeof DrawerLayoutMeIndexRoute
  '/rooms/': typeof DrawerLayoutRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/trial': typeof TrialRoute
  '/auth': typeof DrawerLayoutAuthRouteRouteWithChildren
  '/': typeof DrawerLayoutIndexRoute
  '/auth/login': typeof DrawerLayoutAuthLoginRoute
  '/auth/sign-up': typeof DrawerLayoutAuthSignUpRoute
  '/me/profile': typeof DrawerLayoutMeProfileRoute
  '/me/security': typeof DrawerLayoutMeSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me': typeof DrawerLayoutMeIndexRoute
  '/rooms': typeof DrawerLayoutRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_drawer-layout': typeof DrawerLayoutRouteRouteWithChildren
  '/trial': typeof TrialRoute
  '/_drawer-layout/auth': typeof DrawerLayoutAuthRouteRouteWithChildren
  '/_drawer-layout/me': typeof DrawerLayoutMeRouteRouteWithChildren
  '/_drawer-layout/': typeof DrawerLayoutIndexRoute
  '/_drawer-layout/auth/login': typeof DrawerLayoutAuthLoginRoute
  '/_drawer-layout/auth/sign-up': typeof DrawerLayoutAuthSignUpRoute
  '/_drawer-layout/me/profile': typeof DrawerLayoutMeProfileRoute
  '/_drawer-layout/me/security': typeof DrawerLayoutMeSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_drawer-layout/me/': typeof DrawerLayoutMeIndexRoute
  '/_drawer-layout/rooms/': typeof DrawerLayoutRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trial'
    | '/auth'
    | '/me'
    | '/auth/login'
    | '/auth/sign-up'
    | '/me/profile'
    | '/me/security'
    | '/api/auth/$'
    | '/me/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/trial'
    | '/auth'
    | '/'
    | '/auth/login'
    | '/auth/sign-up'
    | '/me/profile'
    | '/me/security'
    | '/api/auth/$'
    | '/me'
    | '/rooms'
  id:
    | '__root__'
    | '/_drawer-layout'
    | '/trial'
    | '/_drawer-layout/auth'
    | '/_drawer-layout/me'
    | '/_drawer-layout/'
    | '/_drawer-layout/auth/login'
    | '/_drawer-layout/auth/sign-up'
    | '/_drawer-layout/me/profile'
    | '/_drawer-layout/me/security'
    | '/api/auth/$'
    | '/_drawer-layout/me/'
    | '/_drawer-layout/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DrawerLayoutRouteRoute: typeof DrawerLayoutRouteRouteWithChildren
  TrialRoute: typeof TrialRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_drawer-layout': {
      id: '/_drawer-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DrawerLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_drawer-layout/': {
      id: '/_drawer-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DrawerLayoutIndexRouteImport
      parentRoute: typeof DrawerLayoutRouteRoute
    }
    '/_drawer-layout/auth': {
      id: '/_drawer-layout/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof DrawerLayoutAuthRouteRouteImport
      parentRoute: typeof DrawerLayoutRouteRoute
    }
    '/_drawer-layout/me': {
      id: '/_drawer-layout/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof DrawerLayoutMeRouteRouteImport
      parentRoute: typeof DrawerLayoutRouteRoute
    }
    '/_drawer-layout/auth/login': {
      id: '/_drawer-layout/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof DrawerLayoutAuthLoginRouteImport
      parentRoute: typeof DrawerLayoutAuthRouteRoute
    }
    '/_drawer-layout/auth/sign-up': {
      id: '/_drawer-layout/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof DrawerLayoutAuthSignUpRouteImport
      parentRoute: typeof DrawerLayoutAuthRouteRoute
    }
    '/_drawer-layout/me/': {
      id: '/_drawer-layout/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof DrawerLayoutMeIndexRouteImport
      parentRoute: typeof DrawerLayoutMeRouteRoute
    }
    '/_drawer-layout/me/profile': {
      id: '/_drawer-layout/me/profile'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof DrawerLayoutMeProfileRouteImport
      parentRoute: typeof DrawerLayoutMeRouteRoute
    }
    '/_drawer-layout/me/security': {
      id: '/_drawer-layout/me/security'
      path: '/security'
      fullPath: '/me/security'
      preLoaderRoute: typeof DrawerLayoutMeSecurityRouteImport
      parentRoute: typeof DrawerLayoutMeRouteRoute
    }
    '/_drawer-layout/rooms/': {
      id: '/_drawer-layout/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof DrawerLayoutRoomsIndexRouteImport
      parentRoute: typeof DrawerLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DrawerLayoutAuthRouteRouteChildren {
  DrawerLayoutAuthLoginRoute: typeof DrawerLayoutAuthLoginRoute
  DrawerLayoutAuthSignUpRoute: typeof DrawerLayoutAuthSignUpRoute
}

const DrawerLayoutAuthRouteRouteChildren: DrawerLayoutAuthRouteRouteChildren = {
  DrawerLayoutAuthLoginRoute: DrawerLayoutAuthLoginRoute,
  DrawerLayoutAuthSignUpRoute: DrawerLayoutAuthSignUpRoute,
}

const DrawerLayoutAuthRouteRouteWithChildren =
  DrawerLayoutAuthRouteRoute._addFileChildren(
    DrawerLayoutAuthRouteRouteChildren,
  )

interface DrawerLayoutMeRouteRouteChildren {
  DrawerLayoutMeProfileRoute: typeof DrawerLayoutMeProfileRoute
  DrawerLayoutMeSecurityRoute: typeof DrawerLayoutMeSecurityRoute
  DrawerLayoutMeIndexRoute: typeof DrawerLayoutMeIndexRoute
}

const DrawerLayoutMeRouteRouteChildren: DrawerLayoutMeRouteRouteChildren = {
  DrawerLayoutMeProfileRoute: DrawerLayoutMeProfileRoute,
  DrawerLayoutMeSecurityRoute: DrawerLayoutMeSecurityRoute,
  DrawerLayoutMeIndexRoute: DrawerLayoutMeIndexRoute,
}

const DrawerLayoutMeRouteRouteWithChildren =
  DrawerLayoutMeRouteRoute._addFileChildren(DrawerLayoutMeRouteRouteChildren)

interface DrawerLayoutRouteRouteChildren {
  DrawerLayoutAuthRouteRoute: typeof DrawerLayoutAuthRouteRouteWithChildren
  DrawerLayoutMeRouteRoute: typeof DrawerLayoutMeRouteRouteWithChildren
  DrawerLayoutIndexRoute: typeof DrawerLayoutIndexRoute
  DrawerLayoutRoomsIndexRoute: typeof DrawerLayoutRoomsIndexRoute
}

const DrawerLayoutRouteRouteChildren: DrawerLayoutRouteRouteChildren = {
  DrawerLayoutAuthRouteRoute: DrawerLayoutAuthRouteRouteWithChildren,
  DrawerLayoutMeRouteRoute: DrawerLayoutMeRouteRouteWithChildren,
  DrawerLayoutIndexRoute: DrawerLayoutIndexRoute,
  DrawerLayoutRoomsIndexRoute: DrawerLayoutRoomsIndexRoute,
}

const DrawerLayoutRouteRouteWithChildren =
  DrawerLayoutRouteRoute._addFileChildren(DrawerLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DrawerLayoutRouteRoute: DrawerLayoutRouteRouteWithChildren,
  TrialRoute: TrialRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
